#!/bin/bash

RUID=$(who | awk 'FNR == 1 {print $1}')
echo "$RUID"

if [ ! -d "/home/$RUID/.wine" ]; then
  # 32비트 아키텍처 지원 설정
  dpkg --add-architecture i386

  # 공식 wine 저장소 공개키 추가
  wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -

  # wine 저장소 추가
  apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu focal main"

  # wine 설치
  apt update && sudo apt install --install-recommends winehq-stable -y

  # winetricks 설치
  apt install winetricks -y

  # wine 환경설정
  sudo -u $RUID WINEPREFIX=/home/$RUID/.wine WINEARCH=win32 winetricks win10

  # 님프 키보드 중복 입력 Fix 레지스트리 등록
  sudo -u $RUID regedit /usr/lib/linuxmint/mintwelcome/kakaotalk-keybugfix.reg

  # 카톡 다운로드
  wget http://app.pc.kakao.com/talk/win32/KakaoTalk_Setup.exe -P /tmp

  # 설치
  sudo -u $RUID wine /tmp/KakaoTalk_Setup.exe

  sed -i 's/NoDisplay=true/NoDisplay=false/g' /usr/share/applications/kakaotalk-remove.desktop
else

  zenity --info --width 300 --text "재설치가 필요하면\n/home/$RUID/.wine\n디렉토리를 제거해주세요\nsudo rm -r /home/$RUID/.wine\n또는 시작메뉴 > 기타 > 카카오톡 제거를 실행해주세요"

  sed -i 's/NoDisplay=true/NoDisplay=false/g' /usr/share/applications/kakaotalk-remove.desktop
  
fi