#!/bin/bash

RUID=$(who | awk 'FNR == 1 {print $1}')
echo "$RUID"

if [ -d /home/$RUID/.wine ]; then

  rm -rf /home/$RUID/.wine
  rm -rf /home/$RUID/.local/share/applications/wine

  sed -i 's/NoDisplay=false/NoDisplay=true/g' /usr/share/applications/kakaotalk-remove.desktop

  if [ -f /home/$RUID/Desktop/카카오톡.desktop ]; then
    rm /home/$RUID/Desktop/카카오톡.desktop
  elif [ -f /home/$RUID/바탕화면/카카오톡.desktop ]; then
    rm /home/$RUID/바탕화면/카카오톡.desktop
  else
    echo "not found 카카오톡.deskotp"
  fi
  
fi

exit 0